print("\nPer procedere con la calibrazione, eseguire il seguente comando dal terminale, adattandolo alla propria necessità: \n")
print("\npython3 nanocli.py --init --start 10e3 --stop 10e6 --points 101\n")
print("\nVerrà così inizializzato un file calibrazione, con frequenza iniziale 10e3 Hz, frequenza finale 10e6 Hz e 101 punti")
print("Nota, il valore \"101\" dell'esempio riportato non è casuale. Normalmente il NanovnaV2 acquisisce 101 punti di scansione\n\n")

print("Eseguire dunque la vera e propria calibrazione impartendo i seguenti comandi dal terminale\n")
print("python3 nanocli.py --open")
print("python3 nanocli.py --short")
print("python3 nanocli.py --load")
print("python3 nanocli.py --thru")
