print("\n- Per avviare il programma di acquisizione, eseguire il seguente comando dal terminale: ")
print("\npython3 nanocli.py\n\n")
print("- Per avviare il programma salvando i risultati in dB, eseguire il seguente comando:")
print("\npython3 nanocli.py --dB\n\n")
print("- Per avviare il programma salvando i risultati in file s1p, eseguire il seguente comando:")
print("\npython3 nanocli.py --one-port\n\n")
print("- Per avviare il programma salvando un numero di punti specificato (ad esempio 5), eseguire il seguente comando:")
print("\npython3 nanocli.py --points 5\n\n")
print("- E' altresì possibile una combinazione dei precedenti comandi, come nell'esempio seguente:")
print("\npython3 nanocli.py --one-port --dB --points 5\n")
